
name: project cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 17 (using Adoptium Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ensure gradlew is executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the project using the Gradle Wrapper
      - name: Build with Gradle
        run: ./gradlew build

      # Log in to Docker Hub securely using GitHub Secrets
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backendtest:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/backendtest:latest \
                       -f docker/Dockerfile .

      # Verify Docker image exists
      - name: Verify Docker image exists
        run: |
          docker images | grep ${{ secrets.DOCKER_USERNAME }}/backendtest || echo "Docker image not found"

      # Push Docker image to Docker Hub
     # - name: Push Docker image to Docker Hub
      #  run: |
      #    docker push ${{ secrets.DOCKER_USERNAME }}/backendtest:${{ github.sha }}
      #    docker push ${{ secrets.DOCKER_USERNAME }}/backendtest:latest

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/${{secrets.GCP_PROJECT_ID}}/locations/global/workloadIdentityPools/dev-fin-github-resources/subject/SUBJECT_ATTRIBUTE_VALUE  # Replace with your Workload Identity Pool and Provider
          service_account: projets/${{secrets.GCP_PROJECT_ID }}/service/finone-dev-resources @${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ env.GOOGLE_PROJECT_ID }}/finone-backend:${{ github.sha }}
          
          
