name: Project CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 (using Eclipse Adoptium Temurin distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Ensure the Gradle Wrapper is executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the project using the Gradle Wrapper
      - name: Build with Gradle
        run: ./gradlew build

      # Step 5: Log in to Docker Hub securely using GitHub Secrets
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.rishav13 }}
          DOCKER_PASSWORD: ${{ secrets.Rishav@12345# }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t gcr.io/beckendtest/finone-backend:${{ github.sha }} .
